version: "3"
services:
  selenium-hub:
    # hostname: "selenium-hub.local"
    image: selenium/hub:3.141.59-20210929
    container_name: selenium-hub

    # environment:
      # - GRID_TIMEOUT=20
      # - GRID_BROWSER_TIMEOUT=20
      # - GRID_MAX_SESSION=2

    ports:
      - "4444:4444"
    networks:
      - grid 


  firefox:
    image: selenium/node-firefox-debug:3.141.59-20210929
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10

    volumes:
      - /dev/shm:/dev/shm

    

    ports:
      - "5900:5900"

    networks:
      - grid 



networks:

  grid:
