version: '3.7'
services:
  stcourier_scraper_api:
    build: .
    restart: always
    ports:
      - "5000:5000"

    # environment:
    #   - HUB_URI=http://host.docker.internal:4444/wd/hub

    # extra_hosts:
    #   - "host.docker.internal:host-gateway"


